# ชื่อไฟล์: frontend/cloudbuild.yaml

steps:
  # ----------------------------------------------------------------------
  # Step 1: Build the Frontend Docker Image
  # ใช้ Docker builder เพื่อสร้าง Docker Image ของ Frontend
  # ----------------------------------------------------------------------
  - name: "gcr.io/cloud-builders/docker" # Builder image สำหรับคำสั่ง Docker
    args:
      - "build" # คำสั่ง Docker: build image
      - "-t" # ตั้งชื่อและ tag image
      - "asia-southeast1-docker.pkg.dev/$PROJECT_ID/slj-repo/frontend:$COMMIT_SHA" # ชื่อ Image และ Tag (ใช้ $COMMIT_SHA เป็นเวอร์ชัน)
      - "-f" # ระบุ Dockerfile ที่จะใช้
      - "Dockerfile" # ไฟล์ Dockerfile ของ Frontend อยู่ในโฟลเดอร์เดียวกัน
      - "." # Build context คือโฟลเดอร์ปัจจุบัน (frontend/)
    id: BuildFrontendImage # ID สำหรับ Step นี้

  # ----------------------------------------------------------------------
  # Step 2: Push the Frontend Docker Image to Google Artifact Registry
  # เมื่อ Build เสร็จแล้ว ก็ Push Image ไปเก็บที่ Artifact Registry
  # ----------------------------------------------------------------------
  - name: "gcr.io/cloud-builders/docker" # ใช้ Docker builder อีกครั้ง
    args:
      - "push" # คำสั่ง Docker: push image
      - "asia-southeast1-docker.pkg.dev/$PROJECT_ID/slj-repo/frontend:$COMMIT_SHA" # Image ที่จะ Push (ต้องตรงกับชื่อที่ Build)
    id: PushFrontendImage # ID สำหรับ Step นี้

  # ----------------------------------------------------------------------
  # Step 3: Deploy to GCE VM
  # SSH เข้าไปใน GCE VM และรันคำสั่ง Docker Compose เพื่อ Deploy เวอร์ชันใหม่
  # ----------------------------------------------------------------------
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "ssh"
      - "yongsin_oak@slj-instance"
      - "--zone=asia-southeast1-c"
      - "--command"
      - |
        # บน VM ก็ต้องไปที่ root ของโฟลเดอร์ ERP-Front-SLJ ที่คุณ unzip ไว้
        cd /home/yongsin_oak/frontend && \
        docker-compose down && \
        docker pull asia-southeast1-docker.pkg.dev/$PROJECT_ID/slj-repo/frontend:$COMMIT_SHA && \
        docker-compose up -d
    id: DeployFrontendOnGCE
options:
  logging: CLOUD_LOGGING_ONLY
# ----------------------------------------------------------------------
# global substitutions (ตัวแปรที่ Cloud Build มีให้โดยอัตโนมัติ)
# ----------------------------------------------------------------------
# $PROJECT_ID: Project ID ของ Google Cloud ของคุณ
# $COMMIT_SHA: Hash ของ Git commit ที่ Trigger Build นี้
# ----------------------------------------------------------------------
