version: "3.8"

services:
  frontend:
    build: .
    ports:
      - "8080:8080"
    environment:
      VITE_ENV_MODE: production
      VITE_BACKEND_API_URL: ${VITE_BACKEND_API_URL}
    env_file:
      - .env.production
