services:
  frontend-uat:
    image: ${FRONTEND_UAT_IMAGE_TAG}
    restart: always
    ports:
      - "8081:80"
    container_name: frontend-uat
    networks:
      - default

networks:
  default:
    external: false
