#!/usr/bin/env bash
# ngrok-dev.sh — expose frontend (5173) via ngrok
# Vite proxies /api/* → backend localhost:5050 server-side, so only 1 tunnel needed.
# Usage: ./ngrok-dev.sh

set -e

FRONTEND_PORT=5173
NGROK_API="http://localhost:4040/api/tunnels"
ENV_FILE=".env.local"

echo "🚀  Starting ngrok tunnel for frontend ($FRONTEND_PORT)..."

# Kill any existing ngrok
pkill -f "ngrok" 2>/dev/null && sleep 1 || true

# Start ngrok for frontend only
ngrok http $FRONTEND_PORT --log=stdout --log-level=warn &
NGROK_PID=$!

# Wait for ngrok API to be ready
echo "⏳  Waiting for ngrok..."
for i in {1..20}; do
  sleep 1
  if curl -s "$NGROK_API" >/dev/null 2>&1; then
    break
  fi
  if [ $i -eq 20 ]; then
    echo "❌  ngrok failed to start"
    exit 1
  fi
done

sleep 1

# Parse frontend URL
FRONTEND_URL=$(curl -s "$NGROK_API" | python3 -c "
import sys, json
tunnels = json.load(sys.stdin)['tunnels']
for t in tunnels:
    url = t.get('public_url', '')
    if url.startswith('https'):
        print(url)
        break
" 2>/dev/null)

if [ -z "$FRONTEND_URL" ]; then
  echo "⚠️  Could not parse tunnel URL. Check http://localhost:4040"
  wait $NGROK_PID
  exit 0
fi

# Update .env.local — API goes through Vite proxy, so relative path works
cat > "$ENV_FILE" <<EOF
# Auto-generated by ngrok-dev.sh — $(date)
# API calls use Vite proxy: /api/* → localhost:5050 (no separate backend tunnel needed)
VITE_BACKEND_API_URL=/api/v1
VITE_ENV_MODE=development
VITE_BYPASS_AUTH=true
EOF

echo ""
echo "✅  Tunnel ready!"
echo ""
echo "   Frontend : $FRONTEND_URL"
echo "   Backend  : http://localhost:5050 (via Vite proxy)"
echo ""
echo "   $ENV_FILE set to VITE_BACKEND_API_URL=/api/v1"
echo ""
echo "📋  Next steps:"
echo "   1. Start backend  : cd ../ERP-Back-SLJ && bun run start:dev"
echo "   2. Start frontend : bun run dev"
echo "   3. Open on mobile : $FRONTEND_URL"
echo ""
echo "   ngrok dashboard  : http://localhost:4040"
echo ""
echo "Press Ctrl+C to stop ngrok"

wait $NGROK_PID
